export const UserData = [
  {
    firstName: "Eren",
    lastName: "Jaegar",
    menu: "spciy seasoned seafood noodles",
    payment: 1.45,
    status: "preparing",
  },
  {
    firstName: "Yes",
    lastName: "last",
    menu: "spciy seasoned od noodles",
    payment: 14.45,
    status: "pending",
  },
  {
    firstName: "john",
    lastName: "smith",
    menu: "spciy seasoned",
    payment: 14.45,
    status: "complete",
  },
  {
    firstName: "will",
    lastName: "kim",
    menu: "cookie",
    payment: 14.45,
    status: "pending",
  },
  {
    firstName: "Eren",
    lastName: "Jaegar",
    menu: "spciy seasoned seafood noodles",
    payment: 1.45,
    status: "preparing",
  },
  {
    firstName: "Yes",
    lastName: "last",
    menu: "spciy seasoned od noodles",
    payment: 14.45,
    status: "pending",
  },
  {
    firstName: "john",
    lastName: "smith",
    menu: "spciy seasoned",
    payment: 14.45,
    status: "complete",
  },
  {
    firstName: "will",
    lastName: "kim",
    menu: "cookie",
    payment: 14.45,
    status: "pending",
  },
];
